### PR TITLE
Add an option to turn off typing indicator system entirely

### PR DESCRIPTION
**Pull request by ray1997**
Just to pleased this guy: https://github.com/UWPCommunity/Quarrel/issues/51

### CODE REVIEW

**Comment by MarcAnt01** [comment]
Will that affect just self-typing or typing in general?

**Comment by ray1997** [comment]
@MarcAnt01 yes

**Comment by MarcAnt01** [comment]
So, typing will remain and self-typing not🤔?

**Comment by ray1997** [comment]
@MarcAnt01 No, the whole "... is typing" get ignore. Nothing is update at all

**Comment by MarcAnt01** [comment]
Well, I think that feature is useful, but not with self typing as it does happen in official clients

**Pull request merged**
